version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: bitriseio/android-ndk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "flac/build.gradle" }}-{{ checksum "opus/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "flac/build.gradle" }}-{{ checksum "opus/build.gradle" }}
      - run:
          name: Assemble
          command: ./gradlew assembleDebug assembleRelease
